import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'

import '../globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  return (
    <ClerkProvider>
      <html lang={locale}>
        <body>{children}</body>
      </html>
    </ClerkProvider>
  )
}
